### ISSUE TITLE
[Feature Request] SpellIDs to "Adventure Guide"

### ISSUE THREAD

**Issue by Tga123** [ItsJustMeChris/idTip-Community-Fork#30]
How about to add IDs to spells from "Adventure Guide" bosses description?
Something like that:
```lua
local GSI = C_EncounterJournal.GetSectionInfo
C_EncounterJournal.GetSectionInfo = function(sectionID)
	local sectionInfo = GSI(sectionID)
	if sectionInfo and sectionInfo.spellID ~= (nil or 0) then
		sectionInfo.title = sectionInfo.title .. " SpellID: " .. tostring(sectionInfo.spellID)
	end
	return sectionInfo
end
```
Or any other implementation by you choice.

**Comment by ItsJustMeChris** [comment]
I've implemented this using tooltips, similar to how achievements are done, but it's possibly not a perfect solution because of blizzards heavy usage of frame pools in the adventure guide, if what I have leads to inaccuracies or issues I think your proposed solution here is probably the best way to deal with these, we'll see though. ( https://github.com/ItsJustMeChris/idTip-Community-Fork/releases/tag/11.0.28 )
